from .models import Blog


def create_blog_entry(session, *, topic, company_url, email_id=None, brand_name=None, blog=None, status="PENDING"):
    entry = Blog(
        topic=topic,
        company_url=company_url,
        email_id=email_id,
        brand_name=brand_name,
        blog=blog or "",
        status=status,
    )
    session.add(entry)
    session.flush()  # populate autogenerated fields
    return entry


def get_blog_by_id(session, blog_id):
    return session.query(Blog).filter(Blog.id == blog_id).one_or_none()


def update_blog_status(session, blog_id, *, status, blog_content=None):
    blog = get_blog_by_id(session, blog_id)
    if not blog:
        raise ValueError(f"Blog with id {blog_id} not found")

    blog.status = status
    if blog_content is not None:
        blog.blog = blog_content

    session.add(blog)
    return blog
