from typing import Optional

from .models import Blog


def get_blog_by_user_and_company(session, *, user_id: str, company_url: str) -> Optional[Blog]:
    return (
        session.query(Blog)
        .filter(Blog.user_id == user_id, Blog.company_url == company_url)
        .order_by(Blog.created_at.desc())
        .first()
    )


def create_blog_entry(
    session,
    *,
    user_id: str,
    topic: str,
    company_url: str,
    email_id: str = None,
    brand_name: str = None,
    blog: Optional[str] = None,
    status: str = "PENDING",
    twitter_post: Optional[str] = None,
    linkedin_post: Optional[str] = None,
    reddit_post: Optional[str] = None,
):
    entry = Blog(
        user_id=user_id,
        topic=[topic] if topic else [],
        company_url=company_url,
        email_id=email_id,
        brand_name=brand_name,
        blogs=[blog] if blog else [],
        status=status,
        twitter_post=[twitter_post] if twitter_post else [],
        linkedin_post=[linkedin_post] if linkedin_post else [],
        reddit_post=[reddit_post] if reddit_post else [],
    )
    session.add(entry)
    session.flush()  # populate autogenerated fields
    return entry


def get_blog_by_id(session, blog_id):
    return session.query(Blog).filter(Blog.id == blog_id).one_or_none()


def update_blog_status(session, blog_id, *, status, blog_content=None, topic: Optional[str] = None):
    blog = get_blog_by_id(session, blog_id)
    if not blog:
        raise ValueError(f"Blog with id {blog_id} not found")

    blog.status = status
    if blog_content is not None:
        blogs = blog.blogs or []
        blogs.append(blog_content)
        blog.blogs = blogs

    if topic:
        topics = blog.topic or []
        if topic not in topics:
            topics.append(topic)
            blog.topic = topics

    session.add(blog)
    session.flush()
    return blog


def append_social_post(session, blog: Blog, platform: str, content: str):
    platform = platform.lower()
    if platform == "twitter":
        posts = blog.twitter_post or []
        posts.append(content)
        blog.twitter_post = posts
    elif platform == "linkedin":
        posts = blog.linkedin_post or []
        posts.append(content)
        blog.linkedin_post = posts
    elif platform == "reddit":
        posts = blog.reddit_post or []
        posts.append(content)
        blog.reddit_post = posts
    else:
        raise ValueError(f"Unsupported platform for saving: {platform}")

    session.add(blog)
    session.flush()
    return blog
